// synapse/types.ts
// GENERATED by scripts/sync_types.py from synapse/schemas.py, synapse/state_machine.py and
// synapse/api_contracts.py. DO NOT EDIT. Run `python scripts/sync_types.py` to regenerate.

export type UUID = string;
export type ISODateTime = string; // ISO 8601 UTC

// ── ENUMS ──

export type RunState =
  | "teacher_setup"
  | "tag_confirmation"
  | "test_ready"
  | "awaiting_student"
  | "attempt_received"
  | "diagnosing"
  | "tailoring"
  | "reviewing"
  | "note_saved"
  | "analysing"
  | "aggregating"
  | "complete";

export type MistakeClassification =
  | "conceptual_gap"
  | "careless_mistake"
  | "contradictory"
  | "unrelated"
  | "empty";

export type TrendLabel =
  | "new"
  | "improving"
  | "stable"
  | "still_weak"
  | "declining";

export type ReviewStatus = "passed" | "failed" | "revision_limit_reached";

// ── DOMAIN MODELS (synapse/schemas.py) ──

export interface ConceptNode {
  id: UUID;
  name: string;
  summary: string;
  prerequisites: string[];
  created_at: ISODateTime;
  updated_at: ISODateTime;
}

export interface CanonicalNote {
  concept_id: UUID;
  markdown: string;
  extracted_concepts: ConceptNode[];
  teacher_confirmed: boolean;
  confirmed_at?: ISODateTime;
  created_at: ISODateTime;
}

export interface TestQuestion {
  id: UUID;
  text: string;
  correct_answer: string;
  options: [string, string, string, string] /* exactly 4 */;
  concept_id: UUID;
}

export interface Test {
  id: UUID;
  concept_id: UUID;
  concept_name: string;
  questions: TestQuestion[];
  created_at: ISODateTime;
}

export interface Attempt {
  student_id: string;
  test_id: UUID;
  concept_id: UUID;
  answers: Record<string, string>;
  score: number;
  total: number;
  submitted_at: ISODateTime;
}

export interface DiagnosisItem {
  question_id: UUID;
  classification: MistakeClassification;
  reason: string;
}

export interface Diagnosis {
  id: UUID;
  student_id: string;
  concept_id: UUID;
  items: DiagnosisItem[];
  mastery_estimate: number;
  trend: TrendLabel;
  created_at: ISODateTime;
}

export interface NoteVersion {
  student_id: string;
  concept_id: UUID;
  version: number;
  markdown: string;
  diagnosis_id?: UUID;
  review_id?: UUID;
  created_at: ISODateTime;
}

export interface ReviewResult {
  id: UUID;
  passed: boolean;
  canonical_coverage: boolean;
  diagnosis_addressed: boolean;
  links_valid: boolean;
  objections: string[];
  status: ReviewStatus;
  created_at: ISODateTime;
}

export interface AnalysisPayload {
  student_id: string;
  concept_id: UUID;
  mastery_estimate: number;
  trend: TrendLabel;
  cycle_number: number;
  created_at: ISODateTime;
}

export interface TeacherConfirmation {
  concept_id: UUID;
  teacher_id: string;
  confirmed: boolean;
  edited_concepts?: ConceptNode[];
  confirmed_at?: ISODateTime;
  timed_out: boolean;
}

export interface GraphEdge {
  from_concept: string;
  to_concept: string;
  relationship: "prerequisite" | "related" | "subconcept";
}

export interface ConceptGraph {
  nodes: ConceptNode[];
  edges: GraphEdge[];
}

export interface ClassAnalytics {
  concept_id: UUID;
  concept_name: string;
  student_count: number;
  average_mastery: number;
  trend_distribution: Partial<Record<TrendLabel, number>>;
  weak_students: string[];
  updated_at: ISODateTime;
}

// ── API REQUEST/RESPONSE (synapse/api_contracts.py) ──

export interface CreateConceptRequest {
  markdown: string;
  concept_name: string;
}

export interface CreateConceptResponse {
  concept: ConceptNode;
  run_id: UUID;
}

export interface PendingTagsResponse {
  run_id: UUID;
  concept_id: UUID;
  concepts: ConceptNode[];
  expires_at: ISODateTime;
}

export interface ConfirmTagsRequest {
  run_id: UUID;
  confirmed: boolean;
  edited_concepts?: ConceptNode[];
}

export interface ConfirmTagsResponse {
  run_id: UUID;
  state: RunState;
  test?: Test;
}

export interface TeacherAnalyticsResponse {
  concept_id: UUID;
  concept_name: string;
  analytics: ClassAnalytics;
}

export interface TeacherTrendsResponse {
  concept_id: UUID;
  trends: AnalysisPayload[];
}

export interface SubmitAttemptRequest {
  test_id: UUID;
  answers: Record<string, string>;
}

export interface SubmitAttemptResponse {
  run_id: UUID;
  attempt: Attempt;
  diagnosis: Diagnosis;
  note: NoteVersion;
  review: ReviewResult;
  analysis: AnalysisPayload;
}

export interface StudentNotesResponse {
  notes: NoteVersion[];
}

export interface StudentGraphResponse {
  nodes: ConceptNode[];
  edges: GraphEdge[];
}

export interface RunStatusResponse {
  run_id: UUID;
  state: RunState;
  current_cycle: number;
  revision_count: number;
  model_call_count: number;
  error?: string;
}

export interface ErrorResponse {
  error: string;
  message: string;
  details: Record<string, unknown>;
}

// ── CONSTANTS ──

export const MAX_REVISIONS_PER_CYCLE = 3;
export const MAX_MODEL_CALL_RETRIES = 3;
export const TAG_CONFIRMATION_TIMEOUT_SECONDS = 600;
export const MASTERY_WEAK_THRESHOLD = 0.5;
export const DEFAULT_MASTERY_ESTIMATE = 0.5;

