// frontend/src/shared/brainData.ts
import type { ConceptNode, GraphEdge, Test } from '../types/synapse';

export interface BrainNode extends ConceptNode {
  category: 'foundations' | 'algorithms' | 'deep_learning' | 'cognitive_agents';
  x: number;
  y: number;
}

// 24 Interconnected concepts plotted in a dual-hemisphere brain geometry
// Canvas coordinate space: 1000 x 600, Center ~ (500, 300)
export const BRAIN_NODES: BrainNode[] = [
  // ─── LEFT HEMISPHERE: Symbolic Logic & Algorithmic Structures ───
  {
    id: 'c-logic',
    name: 'Propositional Logic',
    summary: 'Boolean algebra, truth tables, and formal deductive inference.',
    prerequisites: [],
    category: 'foundations',
    x: 240,
    y: 160,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-sets',
    name: 'Set Theory & Relations',
    summary: 'Universal sets, mappings, order relations, and equivalence classes.',
    prerequisites: ['c-logic'],
    category: 'foundations',
    x: 180,
    y: 230,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-ds',
    name: 'Linear Data Structures',
    summary: 'Contiguous arrays, dynamic vectors, FIFO queues, and LIFO stacks.',
    prerequisites: ['c-sets'],
    category: 'algorithms',
    x: 210,
    y: 320,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-rec',
    name: 'Recursion & Induction',
    summary: 'Self-referencing procedures, inductive invariants, and stack termination.',
    prerequisites: ['c-ds'],
    category: 'algorithms',
    x: 320,
    y: 260,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-trees',
    name: 'Binary Trees & BSTs',
    summary: 'Hierarchical node partitioning, binary search invariants, and balance.',
    prerequisites: ['c-rec'],
    category: 'algorithms',
    x: 300,
    y: 360,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-graphs',
    name: 'Graph Traversal (DFS/BFS)',
    summary: 'Adjacency structures, topological ordering, and cycle detection.',
    prerequisites: ['c-trees'],
    category: 'algorithms',
    x: 380,
    y: 330,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-dp',
    name: 'Dynamic Programming',
    summary: 'Bellman principle, overlapping subproblems, memoization, and tabulation.',
    prerequisites: ['c-rec'],
    category: 'algorithms',
    x: 390,
    y: 220,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-complexity',
    name: 'Complexity Theory',
    summary: 'Asymptotic bounds (Big-O), P vs NP classes, and space-time tradeoffs.',
    prerequisites: ['c-dp', 'c-graphs'],
    category: 'foundations',
    x: 280,
    y: 450,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ─── RIGHT HEMISPHERE: Continuous Mathematics & Deep Learning ───
  {
    id: 'c-linalg',
    name: 'Linear Algebra & Tensors',
    summary: 'Vector spaces, matrix decomposition, inner products, and tensor ranks.',
    prerequisites: [],
    category: 'foundations',
    x: 760,
    y: 160,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-prob',
    name: 'Probability & Statistics',
    summary: 'Bayes rule, multivariate distributions, expectation, and entropy.',
    prerequisites: [],
    category: 'foundations',
    x: 820,
    y: 230,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-loss',
    name: 'Loss & Empirical Risk',
    summary: 'Cross-entropy, MSE, maximum likelihood, and regularization penalties.',
    prerequisites: ['c-prob', 'c-linalg'],
    category: 'deep_learning',
    x: 790,
    y: 320,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-opt',
    name: 'Optimization & Gradients',
    summary: 'Stochastic gradient descent, Adam optimizer, learning rates, and momentum.',
    prerequisites: ['c-loss'],
    category: 'deep_learning',
    x: 680,
    y: 260,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-mlp',
    name: 'Multi-Layer Perceptrons',
    summary: 'Forward propagation, non-linear activations (GELU/ReLU), and backprop.',
    prerequisites: ['c-opt'],
    category: 'deep_learning',
    x: 700,
    y: 360,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-conv',
    name: 'Convolutional Operators',
    summary: 'Spatial filters, translation equivariance, receptive fields, and pooling.',
    prerequisites: ['c-mlp'],
    category: 'deep_learning',
    x: 720,
    y: 450,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-attn',
    name: 'Self-Attention Mechanism',
    summary: 'Scaled dot-product attention, queries, keys, values, and multi-head heads.',
    prerequisites: ['c-mlp'],
    category: 'deep_learning',
    x: 610,
    y: 330,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-llm',
    name: 'Transformer & LLM Architectures',
    summary: 'Decoder-only autoregressive language modeling, RoPE, and causal masking.',
    prerequisites: ['c-attn'],
    category: 'deep_learning',
    x: 610,
    y: 220,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ─── CENTRAL BRIDGE / CORPUS CALLOSUM: Reasoning & Reinforcement ───
  {
    id: 'c-rl',
    name: 'Markov Decision Processes (RL)',
    summary: 'States, actions, rewards, discount factors, and Bellman optimality.',
    prerequisites: ['c-prob', 'c-dp'],
    category: 'deep_learning',
    x: 500,
    y: 270,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-search',
    name: 'Monte Carlo Tree Search',
    summary: 'Selection, expansion, simulation, and backpropagation for deliberate planning.',
    prerequisites: ['c-trees', 'c-rl'],
    category: 'cognitive_agents',
    x: 500,
    y: 380,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ─── FRONTAL CORTEX (APEX): Autonomous Agent Architectures ───
  {
    id: 'c-memory',
    name: 'Episodic Memory & Vector RAG',
    summary: 'Dense vector retrieval, semantic embeddings, and long-term memory retrieval.',
    prerequisites: ['c-llm', 'c-graphs'],
    category: 'cognitive_agents',
    x: 430,
    y: 130,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-tools',
    name: 'Tool Execution & Function Calling',
    summary: 'Schema synthesis, API orchestration, structured parameter validation.',
    prerequisites: ['c-llm'],
    category: 'cognitive_agents',
    x: 570,
    y: 130,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-state',
    name: 'Durable State Machines',
    summary: 'Append-only event stores, crash-proof resumption, and checkpointing.',
    prerequisites: ['c-tools'],
    category: 'cognitive_agents',
    x: 500,
    y: 70,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-alignment',
    name: 'Constitutional Alignment',
    summary: 'Preference optimization (DPO), critique loops, and guardrail verification.',
    prerequisites: ['c-llm', 'c-rl'],
    category: 'cognitive_agents',
    x: 650,
    y: 90,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-multiagent',
    name: 'Multi-Agent Collective Consensus',
    summary: 'Decentralized debate, specialist delegation, and Byzantine task coordination.',
    prerequisites: ['c-state', 'c-memory', 'c-alignment'],
    category: 'cognitive_agents',
    x: 350,
    y: 90,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-synapse',
    name: 'Synapse Diagnostic Synthesis',
    summary: 'Closed-loop diagnostic cycle, cognitive error classification, and private notes.',
    prerequisites: ['c-multiagent', 'c-state'],
    category: 'cognitive_agents',
    x: 500,
    y: 490,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const BRAIN_EDGES: GraphEdge[] = [
  // Left Hemisphere edges
  { from_concept: 'c-logic', to_concept: 'c-sets', relationship: 'prerequisite' },
  { from_concept: 'c-sets', to_concept: 'c-ds', relationship: 'prerequisite' },
  { from_concept: 'c-ds', to_concept: 'c-rec', relationship: 'prerequisite' },
  { from_concept: 'c-rec', to_concept: 'c-trees', relationship: 'prerequisite' },
  { from_concept: 'c-rec', to_concept: 'c-dp', relationship: 'prerequisite' },
  { from_concept: 'c-trees', to_concept: 'c-graphs', relationship: 'prerequisite' },
  { from_concept: 'c-dp', to_concept: 'c-complexity', relationship: 'prerequisite' },
  { from_concept: 'c-graphs', to_concept: 'c-complexity', relationship: 'prerequisite' },

  // Right Hemisphere edges
  { from_concept: 'c-linalg', to_concept: 'c-loss', relationship: 'prerequisite' },
  { from_concept: 'c-prob', to_concept: 'c-loss', relationship: 'prerequisite' },
  { from_concept: 'c-loss', to_concept: 'c-opt', relationship: 'prerequisite' },
  { from_concept: 'c-opt', to_concept: 'c-mlp', relationship: 'prerequisite' },
  { from_concept: 'c-mlp', to_concept: 'c-conv', relationship: 'prerequisite' },
  { from_concept: 'c-mlp', to_concept: 'c-attn', relationship: 'prerequisite' },
  { from_concept: 'c-attn', to_concept: 'c-llm', relationship: 'prerequisite' },

  // Bridge & Central RL edges
  { from_concept: 'c-prob', to_concept: 'c-rl', relationship: 'prerequisite' },
  { from_concept: 'c-dp', to_concept: 'c-rl', relationship: 'prerequisite' },
  { from_concept: 'c-trees', to_concept: 'c-search', relationship: 'prerequisite' },
  { from_concept: 'c-rl', to_concept: 'c-search', relationship: 'prerequisite' },

  // Frontal Apex & Autonomous Agent edges
  { from_concept: 'c-llm', to_concept: 'c-memory', relationship: 'prerequisite' },
  { from_concept: 'c-graphs', to_concept: 'c-memory', relationship: 'prerequisite' },
  { from_concept: 'c-llm', to_concept: 'c-tools', relationship: 'prerequisite' },
  { from_concept: 'c-tools', to_concept: 'c-state', relationship: 'prerequisite' },
  { from_concept: 'c-llm', to_concept: 'c-alignment', relationship: 'prerequisite' },
  { from_concept: 'c-rl', to_concept: 'c-alignment', relationship: 'prerequisite' },
  { from_concept: 'c-state', to_concept: 'c-multiagent', relationship: 'prerequisite' },
  { from_concept: 'c-memory', to_concept: 'c-multiagent', relationship: 'prerequisite' },
  { from_concept: 'c-alignment', to_concept: 'c-multiagent', relationship: 'prerequisite' },

  // Lower Apex: Synapse Loop
  { from_concept: 'c-multiagent', to_concept: 'c-synapse', relationship: 'prerequisite' },
  { from_concept: 'c-state', to_concept: 'c-synapse', relationship: 'prerequisite' },
  { from_concept: 'c-complexity', to_concept: 'c-synapse', relationship: 'related' },
  { from_concept: 'c-conv', to_concept: 'c-synapse', relationship: 'related' },
];

// Rich Diagnostic Question Bank for Tests across nodes
export const BRAIN_TESTS: Record<string, Test> = {
  'c-logic': {
    id: 'test-logic',
    concept_id: 'c-logic',
    concept_name: 'Propositional Logic',
    created_at: new Date().toISOString(),
    questions: [
      {
        id: 'q-log-1',
        concept_id: 'c-logic',
        text: 'Under what assignment is the implication (P -> Q) strictly FALSE?',
        correct_answer: 'When P is True and Q is False',
        options: [
          'When P is True and Q is False',
          'When P is False and Q is True',
          'When both P and Q are False',
          'When both P and Q are True',
        ],
      },
      {
        id: 'q-log-2',
        concept_id: 'c-logic',
        text: 'What does De Morgan’s Law state regarding the negation of conjunction !(A && B)?',
        correct_answer: '(!A || !B)',
        options: [
          '(!A || !B)',
          '(!A && !B)',
          '(A || B)',
          '!(A || B)',
        ],
      },
    ],
  },
  'c-rec': {
    id: 'test-rec',
    concept_id: 'c-rec',
    concept_name: 'Recursion & Induction',
    created_at: new Date().toISOString(),
    questions: [
      {
        id: 'q-rec-1',
        concept_id: 'c-rec',
        text: 'What is the absolute prerequisite for any recursive procedure to avoid a call stack overflow?',
        correct_answer: 'A base condition that terminates execution without further recursive calls',
        options: [
          'A base condition that terminates execution without further recursive calls',
          'Allocating an auxiliary array with double the input size',
          'Converting all integer variables into 64-bit floating point representations',
          'Enabling compiler-level loop unrolling pragmas',
        ],
      },
      {
        id: 'q-rec-2',
        concept_id: 'c-rec',
        text: 'What is the recurrence relation for the standard Merge Sort algorithm?',
        correct_answer: 'T(n) = 2T(n/2) + O(n)',
        options: [
          'T(n) = 2T(n/2) + O(n)',
          'T(n) = T(n - 1) + O(1)',
          'T(n) = 4T(n/2) + O(n^2)',
          'T(n) = 2T(n/4) + O(1)',
        ],
      },
    ],
  },
  'c-attn': {
    id: 'test-attn',
    concept_id: 'c-attn',
    concept_name: 'Self-Attention Mechanism',
    created_at: new Date().toISOString(),
    questions: [
      {
        id: 'q-att-1',
        concept_id: 'c-attn',
        text: 'Why does Scaled Dot-Product Attention scale by 1 / sqrt(d_k)?',
        correct_answer: 'To prevent large dot products from pushing softmax into regions with vanishing gradients',
        options: [
          'To prevent large dot products from pushing softmax into regions with vanishing gradients',
          'To ensure the attention matrix has zero determinant',
          'To invert the attention matrix into a Hermitian tensor',
          'To reduce sequence length by a factor of d_k',
        ],
      },
      {
        id: 'q-att-2',
        concept_id: 'c-attn',
        text: 'In standard Multi-Head Attention, what is the computational complexity with respect to sequence length N?',
        correct_answer: 'O(N^2) quadratic complexity in attention map calculation',
        options: [
          'O(N^2) quadratic complexity in attention map calculation',
          'O(N log N) quasilinear complexity',
          'O(N) strictly linear complexity',
          'O(2^N) exponential time complexity',
        ],
      },
    ],
  },
  'c-state': {
    id: 'test-state',
    concept_id: 'c-state',
    concept_name: 'Durable State Machines',
    created_at: new Date().toISOString(),
    questions: [
      {
        id: 'q-st-1',
        concept_id: 'c-state',
        text: 'Why does Synapse use an append-only event store instead of mutating state in memory?',
        correct_answer: 'It enables exact auditability, crash-proof process resurrection, and replayability',
        options: [
          'It enables exact auditability, crash-proof process resurrection, and replayability',
          'It eliminates the need for any storage disk or file system',
          'It guarantees zero latency by avoiding all database locks',
          'It prevents any human expert from providing feedback',
        ],
      },
      {
        id: 'q-st-2',
        concept_id: 'c-state',
        text: 'When a run enters a parked state (e.g. tag_confirmation or awaiting_student), what happens to the worker process?',
        correct_answer: 'The process can safely exit; state is stored durably until an event triggers advance',
        options: [
          'The process can safely exit; state is stored durably until an event triggers advance',
          'The process must run a continuous while(true) busy-spin loop',
          'The process aborts and deletes all previous versions',
          'The run is immediately marked as FAILED with timeout',
        ],
      },
    ],
  },
};
