import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

test("Client Contract Alignment: client.ts implements all required endpoints", () => {
  const clientContent = fs.readFileSync(path.resolve(import.meta.dirname, "../src/api/client.ts"), "utf-8");

  // Teacher routes
  assert.ok(clientContent.includes("/teacher/concepts"), "Missing /teacher/concepts endpoint in client");
  assert.ok(clientContent.includes("/teacher/concepts/${runId}/confirm"), "Missing confirm endpoint in client");
  assert.ok(clientContent.includes("/teacher/tests/${runId}"), "Missing tests endpoint in client");
  assert.ok(clientContent.includes("/teacher/analytics/${conceptId}"), "Missing analytics endpoint in client");
  assert.ok(clientContent.includes("/teacher/trends/${conceptId}"), "Missing trends endpoint in client");

  // Student routes
  assert.ok(clientContent.includes("/student/attempts"), "Missing /student/attempts endpoint in client");
  assert.ok(clientContent.includes("/student/notes/${conceptId}"), "Missing /student/notes endpoint in client");
  assert.ok(clientContent.includes("/student/graph"), "Missing /student/graph endpoint in client");

  // Run status
  assert.ok(clientContent.includes("/runs/${runId}/status"), "Missing /runs status endpoint in client");
});

test("Generated types synchronization integrity", () => {
  const typesContent = fs.readFileSync(path.resolve(import.meta.dirname, "../src/types/synapse.ts"), "utf-8");
  assert.ok(typesContent.includes("GENERATED by scripts/sync_types.py"), "types.ts header must indicate generated source");
  assert.ok(typesContent.includes("export interface ConceptNode"), "Missing ConceptNode type");
  assert.ok(typesContent.includes("export interface TestQuestion"), "Missing TestQuestion type");
  assert.ok(typesContent.includes("export interface NoteVersion"), "Missing NoteVersion type");
  assert.ok(typesContent.includes("export interface ReviewResult"), "Missing ReviewResult type");
  assert.ok(typesContent.includes("export interface ClassAnalytics"), "Missing ClassAnalytics type");
});
