#!/usr/bin/env python3
# scripts/sync_types.py
# Generates synapse/types.ts (and its copy frontend/src/types/synapse.ts) from
# synapse/schemas.py + synapse/state_machine.py + synapse/api_contracts.py.
#
#   python scripts/sync_types.py           # regenerate both files
#   python scripts/sync_types.py --check   # CI: exit 1 if either file is stale or the copies differ
from __future__ import annotations

import sys
import types
import typing
from datetime import datetime
from enum import Enum
from pathlib import Path

from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from synapse import api_contracts, schemas, state_machine  # noqa: E402

OUT_PRIMARY = ROOT / "synapse" / "types.ts"
OUT_COPY = ROOT / "frontend" / "src" / "types" / "synapse.ts"

TS_EXCLUDE = {"StudentHistory", "RunScope", "RecordKind"}  # server-only
NON_UUID_IDS = {"student_id", "teacher_id"}  # ids that are opaque strings, not UUIDs
TS_CONSTANTS = [
    "MAX_REVISIONS_PER_CYCLE",
    "MAX_MODEL_CALL_RETRIES",
    "TAG_CONFIRMATION_TIMEOUT_SECONDS",
    "MASTERY_WEAK_THRESHOLD",
    "DEFAULT_MASTERY_ESTIMATE",
]


def _is_union(origin) -> bool:
    return origin is typing.Union or origin is types.UnionType


def ts_type(tp, field_name: str = "") -> str:
    origin, args = typing.get_origin(tp), typing.get_args(tp)
    if _is_union(origin):
        non_none = [a for a in args if a is not type(None)]
        return " | ".join(ts_type(a, field_name) for a in non_none)
    if origin is typing.Literal:
        return " | ".join(f'"{a}"' for a in args)
    if origin in (list, set, frozenset):
        inner = ts_type(args[0])
        return f"({inner})[]" if " | " in inner else f"{inner}[]"
    if origin is tuple:
        return "[" + ", ".join(ts_type(a) for a in args) + "]"
    if origin is dict:
        key, val = ts_type(args[0]), ts_type(args[1])
        if isinstance(args[0], type) and issubclass(args[0], Enum):
            return f"Partial<Record<{key}, {val}>>"
        return f"Record<{key}, {val}>"
    if tp is dict:
        return "Record<string, unknown>"
    if tp is datetime:
        return "ISODateTime"
    if tp is bool:
        return "boolean"
    if tp in (int, float):
        return "number"
    if tp is str:
        is_uuid = field_name == "id" or (field_name.endswith("_id") and field_name not in NON_UUID_IDS)
        return "UUID" if is_uuid else "string"
    if isinstance(tp, type) and (issubclass(tp, Enum) or issubclass(tp, BaseModel)):
        return tp.__name__
    raise TypeError(f"sync_types: unsupported annotation {tp!r} (field '{field_name}')")


def _fixed_length(field) -> int | None:
    lo = hi = None
    for m in field.metadata:
        lo = getattr(m, "min_length", lo)
        hi = getattr(m, "max_length", hi)
    return lo if lo is not None and lo == hi else None


def _is_optional(tp) -> bool:
    return _is_union(typing.get_origin(tp)) and type(None) in typing.get_args(tp)


def emit_enum(e: type[Enum]) -> str:
    values = list(e)
    if len(values) <= 3:
        return f"export type {e.__name__} = " + " | ".join(f'"{v.value}"' for v in values) + ";"
    body = "\n".join(f'  | "{v.value}"' for v in values)
    return f"export type {e.__name__} =\n{body};"


def emit_model(m: type[BaseModel]) -> str:
    lines = [f"export interface {m.__name__} {{"]
    for name, field in m.model_fields.items():
        tp = field.annotation
        optional = _is_optional(tp)
        rendered = ts_type(tp, name)
        n = _fixed_length(field)
        if n and rendered.endswith("[]"):
            rendered = "[" + ", ".join([rendered[:-2]] * n) + f"] /* exactly {n} */"
        lines.append(f"  {name}{'?' if optional else ''}: {rendered};")
    lines.append("}")
    return "\n".join(lines)


def _local(module, kind):
    return [
        obj for obj in vars(module).values()
        if isinstance(obj, type) and issubclass(obj, kind) and obj.__module__ == module.__name__
        and obj is not kind and not obj.__name__.startswith("_") and obj.__name__ not in TS_EXCLUDE
    ]


def generate() -> str:
    out = [
        "// synapse/types.ts",
        "// GENERATED by scripts/sync_types.py from synapse/schemas.py, synapse/state_machine.py and",
        "// synapse/api_contracts.py. DO NOT EDIT. Run `python scripts/sync_types.py` to regenerate.",
        "",
        "export type UUID = string;",
        "export type ISODateTime = string; // ISO 8601 UTC",
        "",
        "// ── ENUMS ──",
        "",
    ]
    enums = _local(state_machine, Enum) + _local(schemas, Enum)
    out += [emit_enum(e) + "\n" for e in enums] + ["// ── DOMAIN MODELS (synapse/schemas.py) ──", ""]
    out += [emit_model(m) + "\n" for m in _local(schemas, BaseModel)]
    out += ["// ── API REQUEST/RESPONSE (synapse/api_contracts.py) ──", ""]
    out += [emit_model(m) + "\n" for m in _local(api_contracts, BaseModel)]
    out += ["// ── CONSTANTS ──", ""]
    out += [f"export const {n} = {getattr(schemas, n)};" for n in TS_CONSTANTS]
    return "\n".join(out) + "\n"


def main() -> int:
    generated = generate()
    if "--check" in sys.argv:
        stale = [p for p in (OUT_PRIMARY, OUT_COPY) if not p.exists() or p.read_text(encoding="utf-8") != generated]
        if stale:
            print("TypeScript types are stale or missing:", *(str(p.relative_to(ROOT)) for p in stale), sep="\n  ")
            print("Run: python scripts/sync_types.py")
            return 1
        print("TypeScript types are in sync.")
        return 0
    for path in (OUT_PRIMARY, OUT_COPY):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(generated, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
